package by.htp.ll.controller.command;

public enum CommandName {
	LOGINATION, REGISTRATION, SAVENEWUSER, GOTOINDEXPAGE, GOTOMAINPAGE,
	LOGOUT, GOTOFULLNEWSPAGE, GOTOEDITPAGE, SAVEEDITEDNEWS, DELETENEWS
}
